### ISSUE TITLE
[Bug]: Rewrite migrations system

### ISSUE THREAD

**Issue by RandomUsername12222** [Monsters-RPG-game/Users#191]
### Time when occurred

N/A

### Reproducibility

100%

### Does this problem occurs while you are logged in ?

No

### Client

N/A

### Steps to reproduce

Run migrations

### What did you expect to happened ?

I've expected to get notified that all migrations finished and non will run

### What actually happened ?

I got information that all migrations run

**Comment by marcin-nedza** [comment]
Cannot reproduce. I suggest building and trying again.
